// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccrucholgsffichvzbpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcnVjaG9sZ3NmZmljaHZ6YnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDQwODQsImV4cCI6MjA3MTE4MDA4NH0.dfHcDD5Eih6ra3c3qx9EL3-I--Ys6n80rI4R7ap0myQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 0
    }
  },
  global: {
    headers: {
      'x-no-realtime': 'true'
    }
  }
});

// Desconectar Realtime WebSocket para economizar egress
supabase.removeAllChannels();